#!/bin/bash
#sudo apt-get install sudo git
#sudo apt-get install emacs-nox tmux
#git clone ...
if ((UID != 0)); then
    printf >&2 '%s: must be run as root\n' "$0"
    exit 1
fi
. conf-puppet

if ! [[ -x /usr/bin/puppet ]]; then
    apt-get update
    apt-get install -y puppet puppet-master
fi

if ! [[ -h /etc/puppet/code/modules ]]; then
    ln -s $PWD/modules /etc/puppet/code/modules
    ln -s $PWD/environments /etc/puppet/code/environments
fi
if grep -q "^search\|^domain" /etc/resolv.conf; then
    echo "Removing domain from resolv.conf"
    sed -i "/^search\|^domain/d" /etc/resolv.conf
    systemctl restart puppet-master
fi

if ! grep -q host01 /etc/hosts; then
    echo "Changing hostname"
    hostnamectl set-hostname host01
    echo "127.0.0.1 host01" >> /etc/hosts
    systemctl restart puppet-master
    echo "Please open a new shell (hostname) and restart bootstrap"
    exit
fi


puppet module install puppetlabs-firewall --version 1
# In version 4.19 and 4.20, the "file_line" is not able to remove "search" and "domain" lines from the container's resolv.conf.
# Since Puppet 4 does not support "union ranges" of versions (only Puppet 5 does, which is currently not included in Debian), require >=4.21.0 and ignore that <=4.18 works as well.
puppet module install puppetlabs-stdlib --version ">=4.21.0"
puppet module install puppetlabs-apt --version 2
puppet module install puppetlabs-postgresql --version 4
puppet module install puppetlabs-mysql --version 3

puppet apply /etc/puppet/code/environments/production/manifests --debug
