#!/bin/bash
targetHost=$1
targetHost=${targetHost%/}
source config
source "$targetHost/config"

echo "To: $to"
echo "Agent: $SSH_AGENT_PID"
oldpid=$SSH_AGENT_PID
if [[ $oldpid == "" ]]; then
    eval $(ssh-agent)
    ssh-add vm-key
fi
command=$(basename -- "$0")
echo "Action: $command"
if [[ $command == "push" ]]; then
    git push -f "$to:" "HEAD:refs/remotes/manager/master"
else
    git fetch "$to:" "+HEAD:refs/remotes/$targetHost/master"
fi
if [[ $oldpid == "" ]]; then
    eval $(ssh-agent -k)
fi

